[package]
name = "lifx"
version = "0.1.0"
authors = ["vagrant"]

[dependencies]
log = "*"
bitflags = "*"
byteorder = "*"
rustc-serialize = "*"
net2 = { version = "*", features = ["nightly"] }

[dev-dependencies]
env_logger = "*"
